import type { User, Project, VideoComment } from "../types"

// Demo Users with different plans
export const demoUsers: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah@example.com",
    avatar: "/placeholder.svg?height=40&width=40&text=SJ",
    role: "client",
    company: "Creative Studio",
    plan: {
      id: "basic",
      name: "Basic Plan",
      price: 45,
      type: "per_video",
      features: ["One professional video edit", "48-hour turnaround", "2 rounds of revisions"],
      projectLimit: 1,
      projectsUsed: 0,
      activeProjects: 0,
      canRequestNewProject: true,
      maxRevisions: 2,
    },
    projects: [
      {
        id: "proj-1",
        title: "Product Launch Video",
        name: "Product Launch Video",
        description: "Marketing video for new product launch campaign",
        status: "completed",
        priority: "medium",
        progress: 100,
        clientId: "1",
        frameioProjectId: "frameio-1",
        frameioAssetId: "asset-1",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        thumbnailUrl: "/placeholder.svg?height=180&width=320&text=Product+Launch",
        duration: 120,
        createdAt: "2024-01-15T10:00:00Z",
        updatedAt: "2024-01-20T15:30:00Z",
        completedAt: "2024-01-20T15:30:00Z",
        revisions: 1,
        maxRevisions: 2,
        canApprove: false,
        canRequestRevision: false,
      },
      {
        id: "proj-2",
        title: "Brand Story Video",
        name: "Brand Story Video",
        description: "Emotional brand storytelling video for website",
        status: "completed",
        priority: "high",
        progress: 100,
        clientId: "1",
        frameioProjectId: "frameio-2",
        frameioAssetId: "asset-2",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        thumbnailUrl: "/placeholder.svg?height=180&width=320&text=Brand+Story",
        duration: 95,
        createdAt: "2024-01-10T09:00:00Z",
        updatedAt: "2024-01-18T14:20:00Z",
        completedAt: "2024-01-18T14:20:00Z",
        revisions: 0,
        maxRevisions: 2,
        canApprove: false,
        canRequestRevision: false,
      },
    ],
    totalSpent: 90,
    memberSince: "Jan 2024",
    memberDays: 580,
  },
  {
    id: "2",
    name: "Mike Chen",
    email: "mike@example.com",
    avatar: "/placeholder.svg?height=40&width=40&text=MC",
    role: "client",
    company: "Tech Startup",
    plan: {
      id: "monthly_pass",
      name: "Monthly Pass Plan",
      price: 350,
      type: "monthly",
      features: ["10 videos per month", "48-hour turnaround per video", "2 rounds of revisions per video"],
      projectLimit: 10,
      projectsUsed: 7,
      activeProjects: 1,
      canRequestNewProject: false,
      monthlyReset: "2024-02-01T00:00:00Z",
      maxRevisions: 2,
    },
    projects: [
      {
        id: "proj-3",
        title: "Social Media Campaign",
        name: "Social Media Campaign",
        description: "Series of short videos for social media marketing",
        status: "in_review",
        priority: "high",
        progress: 85,
        clientId: "2",
        frameioProjectId: "frameio-3",
        frameioAssetId: "asset-3",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        thumbnailUrl: "/placeholder.svg?height=180&width=320&text=Social+Campaign",
        duration: 30,
        createdAt: "2024-01-20T11:00:00Z",
        updatedAt: "2024-01-25T16:45:00Z",
        dueDate: "2024-02-05T17:00:00Z",
        revisions: 1,
        maxRevisions: 2,
        canApprove: true,
        canRequestRevision: true,
      },
    ],
    totalSpent: 350,
    memberSince: "Nov 2023",
    memberDays: 641,
  },
  {
    id: "3",
    name: "Alex Rivera",
    email: "alex@example.com",
    avatar: "/placeholder.svg?height=40&width=40&text=AR",
    role: "client",
    company: "Marketing Agency",
    plan: {
      id: "premium",
      name: "Premium Plan",
      price: 500,
      type: "per_video",
      features: ["One premium edit", "3-4 day turnaround", "2 rounds of revisions"],
      projectLimit: 1,
      projectsUsed: 0,
      activeProjects: 0,
      canRequestNewProject: true,
      maxRevisions: 2,
    },
    projects: [
      {
        id: "proj-4",
        title: "Corporate Presentation",
        name: "Corporate Presentation",
        description: "High-end corporate presentation video with motion graphics",
        status: "completed",
        priority: "high",
        progress: 100,
        clientId: "3",
        frameioProjectId: "frameio-4",
        frameioAssetId: "asset-4",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        thumbnailUrl: "/placeholder.svg?height=180&width=320&text=Corporate+Presentation",
        duration: 180,
        createdAt: "2024-01-05T08:00:00Z",
        updatedAt: "2024-01-15T16:30:00Z",
        completedAt: "2024-01-15T16:30:00Z",
        revisions: 2,
        maxRevisions: 2,
        canApprove: false,
        canRequestRevision: false,
      },
    ],
    totalSpent: 1500,
    memberSince: "Sep 2023",
    memberDays: 702,
  },
  {
    id: "4",
    name: "Emma Thompson",
    email: "emma@example.com",
    avatar: "/placeholder.svg?height=40&width=40&text=ET",
    role: "client",
    company: "Enterprise Corp",
    plan: {
      id: "ultimate",
      name: "Ultimate Plan",
      price: 999,
      type: "monthly",
      features: ["One active project a day", "24-hour turnaround per edit", "Multiple rounds of revisions per video"],
      projectLimit: "unlimited",
      projectsUsed: 15,
      activeProjects: 0,
      canRequestNewProject: true,
      monthlyReset: "2024-02-01T00:00:00Z",
      maxRevisions: 999,
    },
    projects: [
      {
        id: "proj-5",
        title: "Training Series",
        name: "Training Series",
        description: "Comprehensive employee training video series",
        status: "completed",
        priority: "medium",
        progress: 100,
        clientId: "4",
        frameioProjectId: "frameio-5",
        frameioAssetId: "asset-5",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
        thumbnailUrl: "/placeholder.svg?height=180&width=320&text=Training+Series",
        duration: 300,
        createdAt: "2024-01-01T09:00:00Z",
        updatedAt: "2024-01-10T17:00:00Z",
        completedAt: "2024-01-10T17:00:00Z",
        revisions: 1,
        maxRevisions: 999,
        canApprove: false,
        canRequestRevision: false,
      },
    ],
    totalSpent: 2997,
    memberSince: "Jun 2023",
    memberDays: 794,
  },
]

// Demo Comments for projects
export const demoComments: VideoComment[] = [
  {
    id: "comment-1",
    projectId: "proj-3",
    videoId: "asset-3",
    userId: "2",
    userName: "Mike Chen",
    userRole: "client",
    userAvatar: "/placeholder.svg?height=32&width=32&text=MC",
    content: "The intro looks great! Can we make the logo animation a bit faster and add more dynamic transitions?",
    startTime: 5,
    endTime: 10,
    timestamp: 5,
    createdAt: "2024-01-24T14:30:00Z",
    updatedAt: "2024-01-24T14:30:00Z",
    resolved: false,
    replies: [],
    type: "revision_request",
    priority: "medium",
  },
  {
    id: "comment-2",
    projectId: "proj-3",
    videoId: "asset-3",
    userId: "2",
    userName: "Mike Chen",
    userRole: "client",
    userAvatar: "/placeholder.svg?height=32&width=32&text=MC",
    content: "Perfect color grading on this section. Exactly what we were looking for!",
    startTime: 15,
    endTime: 20,
    timestamp: 15,
    createdAt: "2024-01-24T15:00:00Z",
    updatedAt: "2024-01-24T15:00:00Z",
    resolved: true,
    resolvedAt: "2024-01-24T15:00:00Z",
    replies: [],
    type: "approval",
    priority: "low",
  },
]

// Demo Projects for all users
export const demoProjects: Project[] = demoUsers.flatMap((user) => user.projects || [])
